<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>cirru</string>
		<string>cr</string>
	</array>
	<key>name</key>
	<string>Cirru</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.cirru</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.cirru</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\b[\d\.]+\b</string>
			<key>name</key>
			<string>constant.numeric.cirru</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?=^)\s*\,</string>
			<key>name</key>
			<string>keyword.operator.cirru</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?=^)\s*[^\(\)\s\$][^\(\)\s]*</string>
			<key>name</key>
			<string>entity.function.cirru</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=\()[^\(\)\s\$][^\(\)\s]*</string>
			<key>name</key>
			<string>entity.function.cirru</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?=\$\s+)[^\(\)\s\$][^\(\)\s]*</string>
			<key>name</key>
			<string>entity.function.cirru</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\s\$\s*$</string>
			<key>name</key>
			<string>keyword.operator.cirru</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.cirru</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.function.cirru</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\s+((\$\s+)+)([^\(\)\s\$][^\(\)\s]*)</string>
			<key>name</key>
			<string>entity.cirru</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[\)\(]</string>
			<key>name</key>
			<string>keyword.operator.cirru</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?!=($\s+))[^\(\)\s\$][^\(\)\s]*</string>
			<key>name</key>
			<string>variable.parameter.cirru</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.cirru</string>
	<key>uuid</key>
	<string>43471e40-4ccc-45e8-b003-29a2b4f7c191</string>
</dict>
</plist>
